version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - docker/docker_env.local
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

    environment:
      - "POSTGRES_PASSWORD=cnch_password"
      - "POSTGRES_USER=cnch_user"
      - "POSTGRES_DB=cnch_db"


